# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0
# https://github.com/bitnami/containers/tree/main/bitnami/wordpress-nginx

services:
  mariadb:
    container_name: wordpress_docker_db_2
    image: docker.io/bitnami/mariadb:11.4
    restart: unless-stopped
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      # - './mariadb-data:/bitnami/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    env_file: .env
    networks:
      - wp_docker_clean_install_network

  wordpress:
    container_name: wordpress_docker_app_2
    image: docker.io/bitnami/wordpress-nginx:6
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      # - './wordpress:/bitnami/wordpress'
      - 'wordpress_data:/bitnami/wordpress'
      - './bitnami/php-fpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf:ro'
      - './bitnami/php/php.ini:/opt/bitnami/php/etc/php.ini:ro'
      - ./bitnami/nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:ro
    depends_on:
      - mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    env_file: .env
    networks:
      - wp_docker_clean_install_network

# volumes:
#   mariadb_data:
#     driver: local
#   wordpress_data:
#     driver: local

networks:
  wp_docker_clean_install_network:
    driver: bridge
